---
# tasks file for kibana

- set_fact:
    kibana_build_path:  "{{ docker_volumes_path }}/kibana/build"

- set_fact:
    kibana_elastic_bind_ip: "{{ hostvars[groups['elasticsearch'][0]]['ansible_eth0'].ipv4.address }}"
  when: hostvars[groups['elasticsearch'][0]]['ansible_eth0'] is defined

- set_fact:
    kibana_elastic_bind_ip: "{{ hostvars[groups['elasticsearch'][0]]['ansible_wlan0'].ipv4.address }}"
  when: hostvars[groups['elasticsearch'][0]]['ansible_wlan0'] is defined


- name: create build tmp directories
  file: 
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ kibana_build_path }}"

- name: copy dockerfile
  template: 
    src: "{{ item }}" 
    dest: "{{ kibana_build_path }}"
  with_items:
    - Dockerfile
    - kibana.yml
    - entrypoint.sh

- name: build docker image
  docker_image:
      name: pelk-kibana
      path: "{{ kibana_build_path }}"
      state: build

- name: start docker container
  docker:
    name:  pelk-kibana
    image: pelk-kibana
    state: restarted
    volumes: "{{ kibana.docker.volumes }}"
    ports: "{{ kibana.docker.ports }}"

- name: delete build tmp directories
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ kibana_build_path }}"
