---
# task file for elasticsearch

- name: elasticsearch | set default variable
  set_fact: 
    elasticsearch_conf_path: "{{ docker_volumes_path }}/elasticsearch/conf"
    elasticsearch_log_path:  "{{ docker_volumes_path }}/elasticsearch/logs"
    elasticsearch_data_path:  "{{ docker_volumes_path }}/elasticsearch/data"

- name: elasticsearch | create conf and log directories
  file: path={{ item }} state=directory mode=0777
  with_items:
    - "{{ elasticsearch_log_path }}"
    - "{{ elasticsearch_conf_path }}"

- name: elasticsearch | start docker container
  docker:
    name:  elasticsearch
    image: elasticsearch:1.5.2
    state: restarted
    volumes: 
    # - "{{ elasticsearch_conf_path }}:/usr/share/elasticsearch/config"
     - "{{ elasticsearch_data_path }}:/usr/share/elasticsearch/data"
    ports: "{{ docker_elasticsearch_ports }}"
    command: elasticsearch


- name: elasticsearch | set ip
  command: /usr/bin/docker inspect -f \{\{.NetworkSettings.IPAddress\}\} elasticsearch
  register: elasticsearch_ip
