---
# tasks file for packetbeat

- set_fact:
    packetbeat_build_path:  "{{ docker_volumes_path }}/packetbeat/build"

- set_fact:
    packetbeat_elastic_bind_ip: "{{ hostvars[groups['elasticsearch'][0]]['ansible_eth0'].ipv4.address }}"
  when: hostvars[groups['elasticsearch'][0]]['ansible_eth0'] is defined

- set_fact:
    packetbeat_elastic_bind_ip: "{{ hostvars[groups['elasticsearch'][0]]['ansible_wlan0'].ipv4.address }}"
  when: hostvars[groups['elasticsearch'][0]]['ansible_wlan0'] is defined


- name: create build tmp directories
  file: path={{ item }} state=directory mode=0777
  with_items:
    - "{{ packetbeat_build_path }}"

- name: copy dockerfile
  template: 
    src: "{{ item }}" 
    dest: "{{ packetbeat_build_path }}"
  with_items:
    - Dockerfile
    - packetbeat-entrypoint.sh
    - packetbeat.conf

- name: build docker image
  docker_image:
      name: "pelk-packetbeat"
      path: "{{ packetbeat_build_path }}"
      state: build

- name: start docker container
  docker:
    name:  pelk-packetbeat
    image: pelk-packetbeat
    state: reloaded
    net: host

- name: clean tmp directory
  file: 
    path: "{{ packetbeat_build_path }}"
    state: absent